name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build -t mingyen066/react-test -f ./client/Dockerfile.dev ./client
    - run: docker run -e CI=true mingyen066/react npm test
    
    - run: docker build -t mingyen066/multi-client ./client
    - run: docker build -t mingyen066/multi-nginx ./nginx
    - run: docker build -t mingyen066/multi-server ./server
    - run: docker build -t mingyen066/multi-worker ./worker

    - run: docker push mingyen066/multi-client
    - run: docker push mingyen066/multi-nginx
    - run: docker push mingyen066/multi-server
    - run: docker push mingyen066/multi-worker
